version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true

branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

skip_commits:
  message: /skip\-build/
  files:
    - .vscode/
    - README.md
    - .gitattributes
    - .gitignore

install:
  - ps: npm install -g vsce
  - ps: Set-Location $env:APPVEYOR_BUILD_FOLDER

build_script:
  - ps: .\build.ps1

on_finish:
  - ps: .\build.ps1 -Push